### ISSUE TITLE
No clear mapping between likelihood scores and amino acid

### ISSUE THREAD

**Issue by wjs20** [TobiasHeOl/AbLang#1]
Hi Tobias 

I may be missing something in the documentation, but I can't find anything explaining which likelihood maps to which residue.

When you call heavy_ablang(seqs, mode = 'likelihood'), you get an (n_seqs, seq_len, 20) shape array out. I assume the shape 20 array is the 20 amino acids, with each item corresponding to the probality of a given amino acid occuring at that position given the context. 

The problem is, its just a list of probabilities. Which probability corresponds to tyrosine, which to valine etc.

Maybe you could include something in your documentation like {0: A, 1: C ... 20: V} (if that is the ordering).

Thanks

**Comment by TobiasHeOl** [comment]
Hi! 

You are completely right, I haven't made it clear which value corresponds to which amino acid. I will make sure to add some documentation describing this! 

In the meantime, the order is as follows:

{0: 'M',
 1: 'R',
 2: 'H',
 3: 'K',
 4: 'D',
 5: 'E',
 6: 'S',
 7: 'T',
 8: 'N',
 9: 'Q',
 10: 'C',
 11: 'G',
 12: 'P',
 13: 'A',
 14: 'V',
 15: 'I',
 16: 'F',
 17: 'Y',
 18: 'W',
 19: 'L'}

Thank you for letting me know!

Best,
Tobias

**Comment by wjs20** [comment]
Hi Tobias, Thanks for getting back to me. 

Yes thats the ordering that I worked out.

I did 
```python
[dict(set(list(zip(t.tolist()[1:-1],seq)))) for t, seq in zip(heavy_ablang.tokenizer(seqs), seqs)][0]
```
and then sorted it which gave me
```python
{
    1: 'M',
    2: 'R',
    3: 'H',
    4: 'K',
    5: 'D',
    6: 'E',
    7: 'S',
    8: 'T',
    9: 'N',
    10: 'Q',
    11: 'C',
    12: 'G',
    13: 'P',
    14: 'A',
    15: 'V',
    16: 'I',
    17: 'F',
    18: 'Y',
    19: 'W',
    20: 'L'
}
```

I also realized that the method doesn't return probabilities it returns likelihoods (which you do point out in the docs). Probabilites would be a more useful output in my opinion, which I did like this.

```python
res = torch.nn.functional.softmax(torch.tensor(likelihoods), dim = -1)
```
then you can do something like this with it.

![image](https://user-images.githubusercontent.com/70591703/167316466-d3a6b331-4435-4156-b02d-7ebe4f903c79.png)

**Comment by TobiasHeOl** [comment]
Love the figure - probabilities are definitely a nicer output! 

For convenience, you can also access the vocab dictionary directly from the tokenizer with the following:

```python
ablang_vocab = heavy_ablang.tokenizer.vocab_to_aa
```

which gives you the full vocab

```python
{0: '<',
 21: '-',
 22: '>',
 23: '*',
 1: 'M',
 2: 'R',
 3: 'H',
 4: 'K',
 5: 'D',
 6: 'E',
 7: 'S',
 8: 'T',
 9: 'N',
 10: 'Q',
 11: 'C',
 12: 'G',
 13: 'P',
 14: 'A',
 15: 'V',
 16: 'I',
 17: 'F',
 18: 'Y',
 19: 'W',
 20: 'L'}
```

However, it's still confusing how the index of the likelihood output is shifted by one, so I will add some documentation clarifying this.

Again, thanks for pointing this out!

**Comment by TobiasHeOl** [comment]
We have added some more documentation [8f901e9](https://github.com/TobiasHeOl/AbLang/commit/8f901e99fd0ec6cedf12204f89b1de2cc76edbd4).
