### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by cmahervir** [TobiasHeOl/AbLang#2]
Dear Authors, 

I get the following error when installing AbLang via pip, or directly from git. It looks like maybe it is expecting to be deleting a file, but instead it's a directory. Are you seeing the same behavior? Or is this a python version issue? Thanks for your help!:
```
          return self._get_build_requires(
        File "/tmp/pip-build-env-gzvrkc_f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-gzvrkc_f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 217, in <module>
          os.unlink(fairseq_examples)
      IsADirectoryError: [Errno 21] Is a directory: 'fairseq/examples'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by TobiasHeOl** [comment]
Hi @cmahervir.

Thank you for interest in AbLang! Unfortunately this is a known issue with fairseq 0.10.1 and 0.10.2 (see facebookresearch/fairseq#3535) . A possible workaround is to do:

`python
pip install fairseq==0.10.0
`

I hope this helps! I'll keep this issue open until fairseq is properly fixed. 

Best,
Tobias

**Comment by TobiasHeOl** [comment]
Sorry for the long wait! fairseq keeps introducing different dependency issues. To resolve this, we have decided to extract the code from fairseq that we use, allowing us not to install fairseq anymore [8f901e9](https://github.com/TobiasHeOl/AbLang/commit/8f901e99fd0ec6cedf12204f89b1de2cc76edbd4).
