### ISSUE TITLE
Different length sequences in "likelihood" mode

### ISSUE THREAD

**Issue by ElArkk** [TobiasHeOl/AbLang#4]
Hi again,

When passing a list of different length sequences to AbLang in likelihood mode, e.g.:
```python
heavy_ablang = ablang.pretrained("heavy", device="cpu")
heavy_ablang.freeze()
likelihoods = heavy_ablang(["HASTA", "FTA", "LASTA"], mode="likelihood")
```
The returned likelihoods are of shape `(n_seqs, max_seq_len, 20)`.

I was wondering how padding occurs here? There is an unused `align` argument in the source (https://github.com/oxpig/AbLang/blob/main/ablang/pretrained.py#L155), and so I'm assuming padding just happens at the end of the shorter sequences, irrespective of what we set `align` to?

Thanks!

**Comment by TobiasHeOl** [comment]
Hi ElArkk,

Padding always occurs inside the tokenizer before the tokens are given to AbLang. The align argument is alignment of the output to an antibody numbering scheme using ANARCI. This argument has only been implemented for the 'restore' and 'rescoding' modes so far (for seqcoding there is not really any use as we average over the sequence, but for likelihoods it could be a relevant feature).

I will add some documentation explaining the align argument better and also add the align functionality to the likelihood mode.

I hope this clears some confusion.

Best,
Tobias

**Comment by ElArkk** [comment]
Hi Tobias,

Thanks for the prompt responses here! Really appreciated. 

Best,
Arkadij

**Comment by TobiasHeOl** [comment]
We have added some more documentation [8f901e9](https://github.com/TobiasHeOl/AbLang/commit/8f901e99fd0ec6cedf12204f89b1de2cc76edbd4).
