### ISSUE TITLE
Acceptable sequence tokens when running seqcoding?

### ISSUE THREAD

**Issue by HyprValent** [TobiasHeOl/AbLang#5]
I was running a seqcoding program for a large dataset that I had prepared. 
The run returned a `KeyError '_'` which I assumed was because the sequences contained underscores that are not valid tokens.
May I ask where I can find the complete list of valid tokens for sequences? It would be nice to automate a process to filter out sequences with invalid tokens.

Thank you!

**Comment by TobiasHeOl** [comment]
Hi and thank you for your interest in AbLang!

You can get the complete list of valid characters and their corresponding tokens with the following;

`
model = ablang.pretrained()
print(model.tokenizer.vocab_to_aa)
`

I recommend to use the mask token for any unknown residue.

I hope this helps you!

Best wishes,
Tobias
